remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
title: Study and Analysis of the BTC-Alpha Network to Identify Influence of Trust Behavior Dynamics
description: ‎
gems:
  - jekyll-mathematical
